
import javax.swing.JOptionPane;

/*
 * Copyright (C) 2017  Norbert Bartko
 *
 * Dieses Programm ist Freie Software: Sie können es unter den Bedingungen
 * der GNU General Public License, wie von der Free Software Foundation,
 * Version 3 der Lizenz oder (nach Ihrer Wahl) jeder neueren
 * veröffentlichten Version, weiterverbreiten und/oder modifizieren.
 * 
 * Dieses Programm wird in der Hoffnung, dass es nützlich sein wird, aber
 * OHNE JEDE GEWÄHRLEISTUNG, bereitgestellt; sogar ohne die implizite
 * Gewährleistung der MARKTFÄHIGKEIT oder EIGNUNG FÜR EINEN BESTIMMTEN ZWECK.
 * Siehe die GNU General Public License für weitere Details.
 * 
 * Sie sollten eine Kopie der GNU General Public License zusammen mit diesem
 * Programm erhalten haben. Wenn nicht, siehe <http://www.gnu.org/licenses/>.
 */

/**
 *
 * @author Norbert Bartko
 */

public class FormMain extends javax.swing.JFrame {

    /**
     * Creates new form FormMain
     */
    public FormMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JScrollPane = new javax.swing.JScrollPane();
        txtBox = new javax.swing.JTextArea();
        btnLoeffeln = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        JScrollPane.setName("JScrollPane"); // NOI18N

        txtBox.setColumns(20);
        txtBox.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 22)); // NOI18N
        txtBox.setRows(5);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Bundle"); // NOI18N
        txtBox.setText(bundle.getString("FormMain.txtBox.text")); // NOI18N
        txtBox.setName("txtBox"); // NOI18N
        JScrollPane.setViewportView(txtBox);

        btnLoeffeln.setText(bundle.getString("FormMain.btnLoeffeln.text")); // NOI18N
        btnLoeffeln.setName("btnLoeffeln"); // NOI18N
        btnLoeffeln.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoeffelnMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 36)); // NOI18N
        jLabel1.setText(bundle.getString("FormMain.jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JScrollPane))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(btnLoeffeln, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 218, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(JScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLoeffeln)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoeffelnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoeffelnMouseClicked
        
        // Ein neues Löffel objekt anlegen
        ClassLoeffelsprache Loeffel = new ClassLoeffelsprache(txtBox.getText());
        
        // Ausgabe String Deklarieren und Initialisieren
        String ausgabe;
        // Umwandeln des Textes in Löffelsprache
        ausgabe = Loeffel.convertToLoeffelsprache();
        
        // Anzahl der Zahlen bis zu einem Zeilenumbruch
        int ZahlenNachUmbruch = 0;
        
        // Den Ganzen text durchgehen
        for (int i = 0 ; i < ausgabe.length() ; i++){
            // Nach 60 Zeichen ein Zeilenumbruch setzen
            if (ZahlenNachUmbruch == 50 ){
                ausgabe = umbruchSetzen(ausgabe, i);
                // Anzahl der Zahlen bis zu einem Zeilenumbruch wieder auf 0 setzen
                ZahlenNachUmbruch=0;
            }
            ZahlenNachUmbruch++;
        }
        
        // Wieder den text in der Textbox ausgeben
        txtBox.setText(ausgabe);
    }//GEN-LAST:event_btnLoeffelnMouseClicked
    /** 
      * Die umbruchSetzen Methode setzt in den eingegebenen 
      * Text nach der eingegebenen Anzahl von Zeichen einen 
      * Zeilenumbruch
      */
    private String umbruchSetzen(String text, int zahl){
        // Temporäre String Variable
        String tmp = "";
        
        // Den text nur bis zur angegebenen Anzahl von Zeichen speichern
        for (int i = 0 ; i < zahl ; i++){
            tmp += text.charAt(i);
        }
        
        // Den Zeichenumbruch nach der angegebenen Anzahl von Zeichen setzen
        tmp += "\r\n";
        
        // Den restlichen Text hinzufügen
        for (int i = zahl ; i < text.length() ; i++){
            tmp += text.charAt(i);
        }
        // den Text mit dem Zeilenumbruch zurückgeben
        return tmp;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JScrollPane;
    private javax.swing.JButton btnLoeffeln;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextArea txtBox;
    // End of variables declaration//GEN-END:variables
}
